--테이블삭제
DROP TABLE MEMBER;
DROP TABLE RESERVATION_LOG;
DROP TABLE SPACE;

--시퀸스 삭제
DROP SEQUENCE log_seq;

--시퀸스 생성(log테이블)
CREATE SEQUENCE log_seq start WITH 1;

--멤버 테이블 생성
CREATE TABLE MEMBER 
(
  USER_ID VARCHAR2(30 BYTE) NOT NULL 
, PASSWORD VARCHAR2(30 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
, GENDER VARCHAR2(30 BYTE) NOT NULL 
, JUMIN VARCHAR2(30 BYTE) NOT NULL 
, MAIL VARCHAR2(200 BYTE) NOT NULL 
, PERIOD NUMBER(5, 0) NOT NULL 
, CLASSROOM VARCHAR2(30 BYTE) NOT NULL 
, CONSTRAINT MEMBER_PK PRIMARY KEY 
);


--space테이블 생성
CREATE TABLE SPACE 
(
  ROOM_NAME VARCHAR2(30 BYTE) NOT NULL 
, ASSIGNED VARCHAR2(30 BYTE) 
, OCCUPANCY NUMBER(2, 0) 
, OTHERS VARCHAR2(30 BYTE) 
, CONSTRAINT SPACE_PK PRIMARY KEY 
  (
    ROOM_NAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SPACE_PK ON SPACE (ROOM_NAME ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

--로그 테이블 생성
CREATE TABLE RESERVATION_LOG 
(
  LOG_SEQ NUMBER(4, 0) DEFAULT 1 NOT NULL 
, USER_ID VARCHAR2(20 BYTE) NOT NULL 
, USER_NAME VARCHAR2(20 BYTE) NOT NULL 
, START_TIME VARCHAR2(20 BYTE) NOT NULL 
, END_TIME VARCHAR2(30 BYTE) 
, ROOM_NAME VARCHAR2(20 BYTE) 
, USE VARCHAR2(200 BYTE) 
, RESERVATION_DATE VARCHAR2(30 BYTE) 
, CONSTRAINT RESERVATION_LOG_PK PRIMARY KEY 
  (
    LOG_SEQ 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RESERVATION_LOG_PK ON RESERVATION_LOG (LOG_SEQ ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE RESERVATION_LOG
ADD CONSTRAINT RESERVATION_LOG_FK1 FOREIGN KEY
(
  USER_ID 
)
REFERENCES MEMBER
(
  USER_ID 
)
ENABLE;

ALTER TABLE RESERVATION_LOG
ADD CONSTRAINT RESERVATION_LOG_FK2 FOREIGN KEY
(
  ROOM_NAME 
)
REFERENCES SPACE
(
  ROOM_NAME 
)
ENABLE;
